name: Frontend Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: frontEndDev

    steps:
    #Check out the repository code
    - name: Checkout Code
      uses: actions/checkout@v4

    #Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 
        cache: 'npm'

    #Install project dependencies
    - name: Install Dependencies
      run: npm ci

    #Build the project
    - name: Build Project
      run: npm run build
      env:
        CI: false
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

    # Trigger Deployment
    - name: Trigger Deploy
      if: success()
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
